Repository stolostron/prometheus, pull requests merged in 2025-01, with the labels that each got.

#89 2.12: Bump x/net and x/crypto
  go.mod
  go.sum
Labels: lgtm, approved

#90 2.11: Bump x/net and x/crypto
  go.mod
  go.sum
Labels: lgtm, approved

#91 2.10: Bump x/net and x/crypto
  go.mod
  go.sum
Labels: lgtm, approved

#92 2.9: Bump x/net and x/crypto
  go.mod
  go.sum
Labels: lgtm

#88 Bump x/net and x/crypto
  go.mod
  go.sum
Labels: lgtm, approved

#93 chore: enable hermetic builds
  .tekton/prometheus-acm-212-pull-request.yaml
  .tekton/prometheus-acm-212-push.yaml
  .tekton/prometheus-acm-213-pull-request.yaml
  .tekton/prometheus-acm-213-push.yaml
Labels: lgtm, approved

#95 [release-2.10] Update promu version to 0.17.0
  Containerfile.operator
  Dockerfile.prow
Labels: approved

#96 [release-2.9] update promu version to 0.17.0
  Dockerfile.prow
Labels: approved
